image_width = 3840
image_height = 2160
rotate = 0
approximation_order = 16
glitch_percentage = 0.001
frames = 1
frame_offset = 0
zoom_scale = 2.0
display_glitches = true
auto_adjust_iterations = true
remove_centre = false
export = "png"

glitch_tolerance = 1.4e-6

probe_sampling = 15

data_storage_interval = 100

valid_iteration_probe_multiplier = 0.01

series_approximation_tiled = true
series_approximation_enabled = true

coloring_type = "iteration"

jitter = false

stripe_scale = 1.0
distance_transition = 10.0

palette_iteration_span = 100.0
palette_offset = 0
palette_cyclic = true

distance_color = false

lighting = true

lighting_direction = 30.0
lighting_azimuth = 35.0
lighting_opacity = 0.75
lighting_ambient = 0.4
lighting_diffuse = 0.5
lighting_specular = 0.5
lighting_shininess = 20